### ISSUE TITLE
Ryan Hyun | Personal Success

### ISSUE THREAD

**Issue by ryanhyun20** [dartmouth-cs98/20w-ensemble#87]
# Ryan Hyun | Personal Goals
*what does success for this class mean to you?*

* I contribute to a meaningful product that can enhance other people's quality of life.
* I learn how to use new technologies and become better at managing my work.
* I become more industrious and able to handle unfamiliarity and stress in a technical or personal context.

## Challenges
*what are some challenges you foresee?*

* My lack of experience with many technologies could mean lots of learning on the fly.
* I may want to bring the project in directions that may contrast with the views of other members of the team.
* In a time crunch, I tend to have trouble getting things done, so I need to finish my work on time and be efficient.

**Comment by timofei7** [comment]
Great goals.  Keep me posted on how things are going and the direction ideas you have.
