### ISSUE TITLE
Personal Success: Soohwan

### ISSUE THREAD

**Issue by soohwan0905** [dartmouth-cs98/20w-ensemble#88]
# Soohwan Park | Personal Goals
*what does success for this class mean to you?*

* I am very comfortable with Unity and C# to the level where I can dive into VR game development afterwards
* I get Hand Tracking working because that's one of the newest experimental features on Oculus that will be widely used from here on out
* I know what a user-friendly UI looks like in VR after seeing users smoothly run through the full extent of the environment
* I know how to manipulate music in VR

## Challenges
*what are some challenges you foresee?*

* Potential merge conflicts hindering our progress
* Getting behind on where we want to be and not having a solid trajectory

**Comment by timofei7** [comment]
Excited about the hand tracking - seems to work pretty decently! 

BTW: tutorial mode is pure 🔥 look awesome!
