### ISSUE TITLE
Bryan Shin | Personal Success

### ISSUE THREAD

**Issue by bryanshin1997** [dartmouth-cs98/20w-ensemble#92]
# Bryan Shin | Personal Goals
*what does success for this class mean to you?*
* I am able to fully understand and implement one of the many score following/tempo tracking algorithms described in online research papers
* I am able to show Ensemble to musician peers, and see that this application not only works but is relevant and desirable.
* I release this application on the VR market for the masses to download and try out. 

## Challenges
*what are some challenges you foresee?*
* A lot of the research papers online use difficult technical jargon and concepts, which I am unfamiliar with.
* This application may be difficult to release officially because it is targeted at such a specific audience of soloist musicians.
* It will be hard to user-test our application because not many people have access to VR headsets. It will be even harder to find musician peers with VR headsets.

**Comment by timofei7** [comment]
I'm pretty excited about the product, great goals.   Agreed about user testing but I think more and more people are getting these headsets so this is very timely.
